import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Belzer firm workflow pilot is registered as one focused solution', () => {
  const app = read('src/App.tsx')
  const manifest = JSON.parse(read('src/proposalManifest.json'))
  const proposal = read('src/BelzerSystemsProposal.tsx')
  const systemsEntry = manifest.find((entry) => entry.id === 'belzer-systems')

  assert.match(app, /BelzerSystemsProposal/)
  assert.match(app, /case 'belzer-systems'/)
  assert.equal(systemsEntry.name, 'Belzer Law: Firm Workflow Pilot')
  assert.equal(systemsEntry.tagline, 'Private firm workspace and shared agent context · $7,900')
  assert.equal(systemsEntry.href, '/proposal/belzer-systems')
  assert.equal(systemsEntry.status, 'Active')
  assert.equal(systemsEntry.access, 'active')

  assert.match(proposal, /A private workspace that connects the firm’s work and context\./)
  assert.match(proposal, /Belzer Firm Workflow Pilot/)
  assert.match(proposal, /One focused internal system/)
  assert.match(proposal, /\$7,900/)
  assert.match(proposal, /Approximately six weeks/)
  assert.match(proposal, /7 to 10 business days/)

  assert.match(proposal, /Private, self-hosted firm workspace configured for Belzer Law/)
  assert.match(proposal, /One shared view of active matters, tasks, priorities, owners, dates, and items requiring review/)
  assert.match(proposal, /Firm contacts and matter relationships connected to the relevant tasks, communications, dates, and files/)
  assert.match(proposal, /Selected email and calendar information brought into the workspace where access permits/)
  assert.match(proposal, /Connections or direct links to Box, PracticePanther, and other approved tools/)
  assert.match(proposal, /Central firm memory for processes, templates, roles, decisions, recurring instructions, and approved matter context/)
  assert.match(proposal, /Voice or chat instructions converted into proposed tasks, assignments, follow-ups, and draft communications/)
  assert.match(proposal, /Email triage, action extraction, and reply drafts prepared with connected firm context and human review/)
  assert.match(proposal, /A review queue for agent-prepared work/)
  assert.match(proposal, /Deadline suggestions prepared from triggering dates and firm-approved rules/)
  assert.match(proposal, /Britt or attorney approval required before any suggested deadline is added to a calendar/)
  assert.match(proposal, /foundation for gradually bringing selected third-party workflows into the private workspace/)
  assert.match(proposal, /That connected context allows an agent to turn spoken or typed instructions into proposed tasks/)
  assert.match(proposal, /selected workflows now handled in third-party tools can be brought into it/)
  assert.match(proposal, /When a third-party tool cannot support a practical direct connection/)
  assert.match(proposal, /Connect current tools, then replace selected functions when useful/)

  assert.match(proposal, /No email, client communication, or external action is sent without human approval/)
  assert.match(proposal, /No legal deadline is published to a calendar without Britt or attorney review and approval/)
  assert.match(proposal, /does not provide legal advice, autonomous legal analysis, or legal research/)
  assert.match(proposal, /does not replace the firm’s complete case-management/)
  assert.match(proposal, /client-facing app, motions bank, large document-review engine/)
  assert.doesNotMatch(proposal, /front door|front desk|rooms where|house in order|morning it creates|silently published|calmer day/i)
  assert.doesNotMatch(proposal, /Client Experience App/)
  assert.doesNotMatch(proposal, /Private iPhone app/)
  assert.doesNotMatch(proposal, /project management/i)
  assert.doesNotMatch(proposal, /\$15,800/)
})

test('Belzer workflow pilot includes provisional front-loaded payments, support, and value math', () => {
  const proposal = read('src/BelzerSystemsProposal.tsx')

  assert.match(proposal, /\['60%', 'At kickoff', '\$4,740'\]/)
  assert.match(proposal, /\['20%', 'After approval of the first working version and core workflow', '\$1,580'\]/)
  assert.match(proposal, /\['20%', 'At team onboarding and pilot launch', '\$1,580'\]/)
  assert.match(proposal, /At kickoff/)
  assert.doesNotMatch(proposal, /50 \/ 25 \/ 25/)
  assert.match(proposal, /Two structured feedback rounds/)
  assert.match(proposal, /30-day stabilization period/)

  assert.match(proposal, /Under 20 hours/)
  assert.match(proposal, /19\.75 hours/)
  assert.match(proposal, /\$400 attorney hour/)
  assert.match(proposal, /transparent break-even math, not a guaranteed savings claim/)

  assert.match(proposal, /Schedule a proposal review/)
  assert.match(proposal, /Review the pilot/)
  assert.match(proposal, /https:\/\/cal\.com\/anchovies\/30min\?overlayCalendar=true/)
  assert.match(proposal, /href="#pilot"/)

  assert.doesNotMatch(proposal, /\$4,500/)
  assert.doesNotMatch(proposal, /\$8,000/)
  assert.doesNotMatch(proposal, /\$8,500/)
  assert.doesNotMatch(proposal, /\$16,000/)
  assert.doesNotMatch(proposal, /Document Review \+ Exhibit Organizer/)
  assert.doesNotMatch(proposal, /Client Clarity System/)
  assert.doesNotMatch(proposal, /\u2014/)
})

test('both previous Belzer proposals remain recorded but render the locked notice', () => {
  const app = read('src/App.tsx')
  const manifest = JSON.parse(read('src/proposalManifest.json'))
  const notice = read('src/components/LockedProposalNotice.tsx')
  const oldBelzer = manifest.find((entry) => entry.id === 'belzer')
  const oldPilot = manifest.find((entry) => entry.id === 'belzer-pilot')

  assert.deepEqual(oldBelzer.paths, ['/proposal/belzer', '/belzer'])
  assert.equal(oldBelzer.status, 'Archived')
  assert.equal(oldBelzer.access, 'locked')
  assert.equal(oldBelzer.showInDashboard, true)
  assert.equal(oldBelzer.sourceFile, 'src/Proposal.tsx')

  assert.deepEqual(oldPilot.paths, ['/proposal/belzer-pilot'])
  assert.equal(oldPilot.status, 'Archived')
  assert.equal(oldPilot.access, 'locked')
  assert.equal(oldPilot.showInDashboard, true)
  assert.equal(oldPilot.sourceFile, 'src/BelzerPilotProposal.tsx')

  assert.match(app, /if \(proposalEntry\.access === 'locked'\)/)
  assert.match(app, /withProposalGate\(<LockedProposalNotice \/>\)/)
  assert.match(notice, /This proposal is no longer available\./)
  assert.match(notice, /This version has been replaced\. Contact Anchovies for the current proposal\./)
})
