import { readFileSync } from 'node:fs'
import test from 'node:test'
import assert from 'node:assert/strict'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Cipher proposal is registered with Paper-sourced brand and website scope', () => {
  const app = read('src/App.tsx')
  const dashboard = read('src/admin/Dashboard.tsx')
  const proposal = read('src/CipherProposal.tsx')
  const contract = read('src/contracts/cipherContract.ts')

  assert.match(app, /CipherProposal/)
  assert.match(app, /cipherContract/)
  assert.match(app, /\/proposal\/cipher/)
  assert.match(app, /\/proposal\/cipher\/contract/)
  assert.match(dashboard, /name: 'Cipher'/)
  assert.match(dashboard, /\/proposal\/cipher/)

  assert.match(proposal, /Complexity, made controlled\./)
  assert.match(proposal, /Cipher exists to make that complexity usable\./)
  assert.match(proposal, /Sleek in form\. Sharp in feeling\./)
  assert.match(proposal, /What the work needs to accomplish\./)
  assert.match(proposal, /A complete brand and website engagement\./)
  assert.match(proposal, /A website that feels intelligent\./)
  assert.match(proposal, /Twenty-nine artifacts/)
  assert.match(proposal, /Focused, efficient, paced for momentum\./)
  assert.match(proposal, /\$15,900/)
  assert.match(proposal, /\$2,500/)
  assert.match(proposal, /\$4,500/)
  assert.match(proposal, /\$7,950/)
  assert.match(proposal, /\$3,975/)
  assert.match(proposal, /Schedule discovery/)
  assert.match(proposal, /Home/)
  assert.match(proposal, /Solutions/)
  assert.match(proposal, /Outcomes/)
  assert.match(proposal, /About/)
  assert.match(proposal, /Contact/)
  assert.doesNotMatch(proposal, /Review contract/)
  assert.doesNotMatch(proposal, /\/proposal\/cipher\/contract/)
  assert.doesNotMatch(proposal, /63 69 70 68 65 72/)
  assert.doesNotMatch(proposal, /You came to us for a brand and website/)

  assert.match(proposal, /§ 01 \/ Overview/)
  assert.match(proposal, /§ 04 \/ Brand direction/)
  assert.match(proposal, /§ 05 \/ Strategic priorities/)
  assert.match(proposal, /§ 06 \/ Scope of work/)
  assert.match(proposal, /§ 07 \/ Website concept/)
  assert.match(proposal, /§ 08 \/ Final deliverables/)
  assert.match(proposal, /§ 09 \/ Process and timeline/)
  assert.match(proposal, /§ 10 \/ Investment/)
  assert.match(proposal, /§ 11 \/ In closing/)
  assert.doesNotMatch(proposal, /§ 12 \//)
  assert.doesNotMatch(proposal, /§ 13 \//)
  assert.doesNotMatch(proposal, /§ 14 \//)
  assert.doesNotMatch(proposal, /Working assumptions/)
  assert.doesNotMatch(proposal, /Next step/)

  assert.match(contract, /Brand Identity \+ Website Engagement/)
  assert.match(contract, /slug: 'cipher'/)
  assert.match(contract, /fee: '\$15,900'/)
  assert.match(contract, /timeline: '4 weeks'/)
  assert.match(contract, /price: '\$2,500'/)
  assert.match(contract, /price: '\$8,000'/)
  assert.match(contract, /amount: '\$7,950'/)
  assert.match(contract, /amount: '\$3,975'/)
  assert.match(contract, /Website design and build/)
  assert.match(contract, /Solutions page design/)
  assert.match(contract, /Outcomes page design/)
  assert.match(contract, /About page design/)
  assert.match(contract, /Contact page design/)
  assert.match(contract, /Responsive desktop and mobile design/)
})
