import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Emergences Labs proposal is routed with the full identity and product system', () => {
  const app = read('src/App.tsx')
  const manifest = read('src/proposalManifest.json')
  const proposal = read('src/EmergencesLabsProposal.tsx')
  const contract = read('src/contracts/emergencesLabsContract.ts')
  const styles = read('src/index.css')

  assert.match(app, /EmergencesLabsProposal/)
  assert.match(app, /case 'emergences-labs'/)
  assert.match(app, /case 'emergences-labs-contract'/)
  assert.match(app, /ContractPage contract=\{emergencesLabsContract\}/)
  assert.match(manifest, /"name": "Emergences Labs"/)
  assert.match(manifest, /\/proposal\/emergences-labs/)
  assert.match(manifest, /"id": "emergences-labs-contract"/)
  assert.match(manifest, /\/proposal\/emergences-labs\/contract/)
  assert.match(manifest, /\$45,000/)

  assert.match(proposal, /Make human capability impossible to overlook\./)
  assert.match(proposal, /The machine is the context\. The human is the subject\./)
  assert.match(proposal, /<Reveal className="grid sm:grid-cols-2">/)
  assert.match(proposal, /The brief is clear\. The answer should still surprise us\./)
  assert.match(proposal, /human, warm, inhabited, classically grounded, grand with restraint/)
  assert.match(proposal, /We understand those as real constraints\./)
  assert.match(proposal, /The brief tells us what must be true\./)
  assert.match(proposal, /The work can still become better than any of us can describe before we begin\./)
  assert.match(proposal, /Considered grandeur/)
  assert.match(proposal, /Clarity as a creative constraint/)
  assert.match(proposal, /compress it into a clear positioning statement/)
  assert.match(proposal, /Existing survey and reference synthesis/)
  assert.match(proposal, /Brand strategy and alignment/)
  assert.match(proposal, /what Emergences Labs really sells, how it creates that value, why it exists, and who it serves/)
  assert.match(proposal, /Light market, category, and competitor research/)
  assert.match(proposal, /Clear brand positioning statement/)
  assert.match(proposal, /One unifying creative idea and brand-world premise/)
  assert.match(proposal, /Messaging, photography, identity, and product-expression direction/)
  assert.match(proposal, /Emergences Labs, NeoWork, and NeoHuman family architecture/)
  assert.match(proposal, /NeoWork product identity and logo system/)
  assert.match(proposal, /NeoHuman product identity and logo system/)
  assert.match(proposal, /One master brand\. Two focused product identities\. One connected system\./)
  assert.match(proposal, /Assessment and results interface studies/)
  assert.match(proposal, /Dashboard and learning-surface studies/)
  assert.match(proposal, /Current product environment and backend software review/)
  assert.match(proposal, /Navigation, forms, tables, cards, empty states, and notifications/)
  assert.match(proposal, /Responsive desktop and mobile product mockups/)
  assert.match(proposal, /Email, event badge, signage, and document mockups/)
  assert.match(proposal, /a broad mockup suite/)
  assert.match(proposal, /representative backend, product, and interface surfaces/)
  assert.match(proposal, /a walkthrough of the current software and product environment/)
  assert.match(proposal, /Logo animation/)
  assert.match(proposal, /Two short motion studies/)
  assert.match(proposal, /Merchandise and event concepts/)
  assert.match(proposal, /Research report or publication template/)
  assert.match(proposal, /Figma design system library/)
  assert.match(proposal, /Direction assurance/)
  assert.match(proposal, /No-cost creative reset if the direction fundamentally misses the agreed outcome/)
  assert.match(proposal, /materially distinct new territory at no additional creative fee/)
  assert.match(proposal, /Approval-gated payment/)
  assert.match(proposal, /Direction-stage exit/)
  assert.match(proposal, /Sean Ashlow, Kira Knoop, and Logan Causey remain the working team throughout/)
  assert.match(proposal, /Full product UX architecture, engineering, and coded websites are not included/)
  assert.match(proposal, /Decision makers start with us/)
  assert.match(proposal, /One day-to-day lead/)
  assert.match(proposal, /one consolidated set of feedback/)

  assert.match(proposal, /Lex Politica/)
  assert.match(proposal, /Wild Hare/)
  assert.match(proposal, /Garza/)
  assert.match(proposal, /Genesi/)
  assert.match(proposal, /\/work\/emergences\/lex-politica\.jpg/)
  assert.match(proposal, /\/work\/emergences\/wild-hare\.jpg/)
  assert.match(proposal, /\/work\/emergences\/garza\.webp/)
  assert.match(proposal, /\/work\/emergences\/genesi\.webp/)
  assert.match(proposal, /pitch\.com\/v\/genesi-pitch-ssispr/)
  assert.match(proposal, /the-brandidentity\.com\/project\/how-did-anchovies-bring-consumer-brand-thinking-to-a-texas-law-firm/)
  assert.match(proposal, /Read the process feature/)
  assert.match(proposal, /The big idea was ancient and modern at once\./)
  assert.match(proposal, /equal parts Washington Post and socialite/)
  assert.match(proposal, /balance the appropriateness of a traditional field with the bravery to pursue something aesthetically distinct/)
  assert.match(proposal, /The big idea was to rethink what a hare or rabbit could be\./)
  assert.match(proposal, /The mythical Wolpertinger became a vessel for creativity and the pursuit of the unexpected/)
  assert.match(proposal, /For Garza, the big idea and the process behind it are best told in The Brand Identity\./)
  assert.match(proposal, /Still in beta and hot off the presses\./)
  assert.match(proposal, /The big idea begins with Marcus Aurelius: a Roman coin recast for a modern political and public affairs company\./)
  assert.match(proposal, /Preview the work/)
  assert.match(proposal, /lg:grid-cols-2/)
  assert.match(proposal, /relative aspect-video overflow-hidden/)
  assert.match(proposal, /aspect-\[3\/4\].*md:aspect-\[16\/9\]/)
  assert.match(proposal, /hover:z-30 focus-visible:z-30/)
  assert.match(proposal, /shadow-\[0_0_0_18px_var\(--color-ink\)\]/)
  assert.match(proposal, /absolute z-40 w-\[190px\]/)

  assert.match(proposal, /Listening/)
  assert.match(proposal, /Culture/)
  assert.match(proposal, /Curiosity/)
  assert.match(proposal, /Empathy/)
  assert.match(proposal, /Decisiveness/)
  assert.match(proposal, /label: 'Love'/)
  assert.match(proposal, /I can explain the steps\. I cannot reduce the process\./)
  assert.match(proposal, /Made in real time/)
  assert.match(proposal, /Before the idea becomes clear\./)
  assert.match(proposal, /<div className="border-y border-paper\/20">/)
  assert.match(proposal, /relative mx-auto aspect-\[3\/4\] max-w-\[1120px\] md:aspect-\[16\/9\]/)
  assert.match(proposal, /Reveal className="emergences-process-field"/)
  assert.match(styles, /\.emergences-labs-proposal > section > \.emergences-process-field/)
  assert.match(styles, /max-width: none;/)
  assert.match(styles, /margin-left: -120px;/)
  assert.match(proposal, /It did not exist before this proposal\./)
  assert.match(proposal, /No fixed beginning/)
  assert.match(proposal, /No fixed center/)
  assert.match(proposal, /An antenna for the frequency underneath the words\./)
  assert.match(proposal, /Having the guts to follow the signal\./)
  assert.match(proposal, /Caring about the work beyond the contract\./)
  assert.match(proposal, /label: 'The big idea'/)
  assert.match(proposal, /A vessel for what makes you special, made clear enough for the world to recognize\./)
  assert.match(proposal, /everything comes together to form the big idea/)
  assert.match(proposal, /The challenge may send me into the woods for two weeks or into a happy hour full of suits\./)
  assert.match(proposal, /The process is mental, environmental, and specific to the question in front of me\./)
  assert.match(proposal, /The route may change, but the thing I am after does not: the big idea\./)
  assert.match(proposal, /attributeName="stroke-dashoffset"/)
  assert.match(proposal, /attributeName="d"/)
  assert.doesNotMatch(proposal, /stroke=\{\(from \+ to\) % 5/)
  assert.match(proposal, /I would like to simplify that for you, but I cannot do it honestly\./)
  assert.match(proposal, /In the mysteries underneath AI, there is a mystery to my creative process too\./)
  assert.match(proposal, /\/signatures\/sean-ashlow\.png/)
  assert.match(proposal, /Founder and Creative Director, Anchovies/)
  assert.match(proposal, /mt-12 border-t border-\[var\(--color-rule\)\] py-12/)
  assert.match(proposal, /index < phases\.length - 1/)

  assert.match(proposal, /\$5,000/)
  assert.match(proposal, /\$17,500/)
  assert.match(proposal, /\$13,000/)
  assert.match(proposal, /\$9,500/)
  assert.match(proposal, /\$45,000/)
  assert.match(proposal, /\$22,500/)
  assert.equal((proposal.match(/\$11,250/g) ?? []).length, 2)
  assert.doesNotMatch(proposal, /\$35,000/)
  assert.doesNotMatch(proposal, /\$14,500/)
  assert.doesNotMatch(proposal, /\$8,500/)
  assert.doesNotMatch(proposal, /\$7,000/)
  assert.doesNotMatch(proposal, /\$8,750/)
  assert.match(proposal, /50% \/ 25% \/ 25%/)
  assert.match(proposal, /\$45,000 · 6 weeks/)
  assert.match(proposal, /right="6 weeks"/)
  assert.match(proposal, /Six-week target/)
  assert.match(proposal, /Weeks 03 to 04/)
  assert.match(proposal, /Week 05/)
  assert.match(proposal, /Week 06/)
  assert.doesNotMatch(proposal, /10 to 12 weeks/)
  assert.doesNotMatch(proposal, /Ten to twelve weeks/)
  assert.match(proposal, /Commissioned separately, three identities of this depth would exceed this investment/)
  assert.match(proposal, /earn a long-term creative relationship/)

  assert.match(proposal, /Schedule proposal review/)
  assert.match(proposal, /Review contract/)
  assert.match(proposal, /\/proposal\/emergences-labs\/contract/)
  assert.match(proposal, /https:\/\/cal\.com\/anchovies\/30min/)
  assert.doesNotMatch(proposal, /[—–]/)

  assert.match(contract, /Three-Brand Identity and Product Design System/)
  assert.match(contract, /fee: '\$45,000'/)
  assert.match(contract, /Emergences Labs master identity/)
  assert.match(contract, /Brand strategy and alignment/)
  assert.match(contract, /Definition of what the company sells, how it delivers value, why it exists, and who it serves/)
  assert.match(contract, /Light market, category, and competitor research/)
  assert.match(contract, /Clear brand positioning statement/)
  assert.match(contract, /One unifying creative idea and brand-world premise/)
  assert.match(contract, /Messaging, photography, identity, and product-expression direction/)
  assert.match(contract, /NeoWork product identity and logo system/)
  assert.match(contract, /NeoHuman product identity and logo system/)
  assert.match(contract, /\$22,500/)
  assert.equal((contract.match(/\$11,250/g) ?? []).length, 2)
  assert.match(contract, /Due after written approval of the Emergences Labs master identity direction/)
  assert.match(contract, /no additional creative fee or preset round cap/)
  assert.match(contract, /written diagnosis of why it missed/)
  assert.match(contract, /materially distinct new territory/)
  assert.match(contract, /retains the \$22,500 kickoff payment and the Client owes no additional project fee/)
  assert.match(contract, /project-specific work created through the termination date/)
  assert.match(contract, /will not publish, sell, repurpose, or use an unselected or abandoned territory/)
  assert.match(contract, /Sean Ashlow, Kira Knoop, and Logan Causey will remain the working Anchovies team throughout/)
  assert.match(contract, /This is not an Emergences Labs-only engagement/)
  assert.doesNotMatch(contract, /[—–]/)
})
