import { readFileSync } from 'node:fs'
import test from 'node:test'
import assert from 'node:assert/strict'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Springstead proposal is registered and preserves source content', () => {
  const app = read('src/App.tsx')
  const dashboard = read('src/admin/Dashboard.tsx')
  const proposal = read('src/GarySpringsteadProposal.tsx')
  const css = read('src/index.css')

  assert.match(app, /GarySpringsteadProposal/)
  assert.match(app, /\/proposal\/gary-springstead/)
  assert.match(dashboard, /Springstead/)
  assert.doesNotMatch(dashboard, /name: 'Gary Springstead'/)
  assert.match(dashboard, /\/proposal\/gary-springstead/)
  assert.match(proposal, /Anchovies × Springstead/)
  assert.match(proposal, /Anchovies x Springstead - Proposal/)
  assert.match(proposal, /A new firm with a reputation already built\./)
  assert.match(proposal, /The core engagement\./)
  assert.match(proposal, /\$23,000/)
  assert.match(proposal, /Budget-adjusted total/)
  assert.match(proposal, /\$16,500/)
  assert.match(proposal, /Original core engagement/)
  assert.match(proposal, /Budget accommodation/)
  assert.match(proposal, /-\$6,500/)
  assert.match(proposal, /\$8,250 reserves the project window and begins discovery\./)
  assert.match(proposal, /\$4,125 is due once the primary brand identity has been presented and approved\./)
  assert.match(proposal, /\$4,125 is due before the final website launch and asset handoff\./)
  assert.match(proposal, /<h1 className="display/)
  assert.doesNotMatch(css, /\.gary-springstead-proposal\s*\{\s*--font-serif/)
  assert.doesNotMatch(proposal, /namingIncludes/)
  assert.doesNotMatch(proposal, /Naming strategy and exploration/)
  assert.doesNotMatch(proposal, /\$20,500 adjusted with naming/)
  assert.doesNotMatch(proposal, /\$27,000/)
  assert.doesNotMatch(proposal, /final naming decision/)
  assert.match(proposal, /Branding Work/)
  assert.match(proposal, /Website Design/)
  assert.match(proposal, /https:\/\/swim-lang\.github\.io\/blanchet-site\/index\.html/)
  assert.match(proposal, /Password: Dolly/)
  assert.match(proposal, /https:\/\/koplow-defense\.framer\.website\//)
  assert.match(proposal, /https:\/\/sidweberlaw\.com\//)
  assert.match(proposal, /https:\/\/toddburnham\.framer\.website\//)
  assert.match(proposal, /https:\/\/mavenadvocacy\.com\//)
  assert.match(proposal, /https:\/\/lexpolitica\.com\//)
  assert.match(proposal, /https:\/\/burnhamlaw\.com\//)
  assert.match(proposal, /https:\/\/belzerlawfirm\.com\//)
  assert.match(proposal, /https:\/\/pitch\.com\/v\/anchovies-press-zwdsbn/)
  assert.match(proposal, /The Brand Identity/)
  assert.match(proposal, /Best Law Firm Websites 2023/)
  assert.match(proposal, /Best Law Firm Websites 2026/)
  assert.match(proposal, /2025 Award: Good vs\. Great/)
  assert.match(proposal, /Schedule proposal review/)
  assert.match(proposal, /View work/)
  assert.match(proposal, /bg-\[var\(--color-mac\)\]/)
  assert.doesNotMatch(proposal, /Schedule kickoff/)
})
