import { readFileSync } from 'node:fs'
import test from 'node:test'
import assert from 'node:assert/strict'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Springstead proposal is registered and preserves source content', () => {
  const app = read('src/App.tsx')
  const manifest = read('src/proposalManifest.json')
  const proposal = read('src/GarySpringsteadProposal.tsx')
  const css = read('src/index.css')

  assert.match(app, /GarySpringsteadProposal/)
  assert.match(manifest, /Springstead/)
  assert.doesNotMatch(manifest, /"name": "Gary Springstead"/)
  assert.match(manifest, /\/proposal\/gary-springstead/)
  assert.match(proposal, /Anchovies × Springstead/)
  assert.match(proposal, /Anchovies x Springstead - Proposal/)
  assert.match(proposal, /A new firm with a reputation already built\./)
  assert.match(proposal, /gary-hero-title/)
  assert.match(css, /\.gary-springstead-proposal \.gary-hero-title/)
  assert.match(proposal, /Core engagement and adjusted budget\./)
  assert.match(proposal, /\$23,000/)
  assert.match(proposal, /Budget-adjusted total/)
  assert.match(proposal, /\$16,500/)
  assert.match(proposal, /Original core engagement/)
  assert.match(proposal, /Budget accommodation/)
  assert.match(proposal, /-\$6,500/)
  assert.match(proposal, /\$8,250 reserves the project window and begins discovery\./)
  assert.match(proposal, /\$4,125 is due once the primary brand identity has been presented and approved\./)
  assert.match(proposal, /\$4,125 is due before the final website launch and asset handoff\./)
  assert.match(proposal, /<h1 className="display/)
  assert.doesNotMatch(css, /\.gary-springstead-proposal\s*\{\s*--font-serif/)
  assert.doesNotMatch(proposal, /namingIncludes/)
  assert.doesNotMatch(proposal, /Naming strategy and exploration/)
  assert.doesNotMatch(proposal, /\$20,500 adjusted with naming/)
  assert.doesNotMatch(proposal, /\$27,000/)
  assert.doesNotMatch(proposal, /final naming decision/)
  assert.match(proposal, /A brand that can turn heads without chasing attention, a website that works as more than a glossy business card, a platform that gives clients, referral counsel, courts, and the media an immediate sense of who is leading the matter and why they are equipped to do it\./)
  assert.match(proposal, /A few things stood out from our conversation\./)
  assert.match(proposal, /Our Work/)
  assert.match(proposal, /What carries forward\./)
  assert.match(proposal, /A sharper first impression for serious work\./)
  assert.match(proposal, /Four systems for one launch\./)
  assert.match(proposal, /A focused path from decision to launch\./)
  assert.match(proposal, /What Springstead receives at launch\./)
  assert.match(proposal, /Four to five weeks, from direction to launch\./)
  assert.match(proposal, /Ready to begin\./)
  assert.doesNotMatch(proposal, /Most criminal defense brands operate from the same narrow playbook/)
  assert.doesNotMatch(proposal, /For more than a decade, Gary’s name has been attached/)
  assert.doesNotMatch(proposal, /This is not a first introduction to the market/)
  assert.doesNotMatch(proposal, /One place to review the shape of the work/)
  assert.doesNotMatch(proposal, /The firm is new\. The credibility is not\./)
  assert.doesNotMatch(proposal, /Make the public expression catch up to the practice\./)
  assert.doesNotMatch(proposal, /Built for the reputation already there\. Designed for what comes next\./)
  assert.doesNotMatch(proposal, /From an established reputation to an independent platform\./)
  assert.doesNotMatch(proposal, /§ 09 — Future opportunities/)
  assert.doesNotMatch(proposal, /§ 11 — In closing/)
  assert.doesNotMatch(proposal, /FutureOpportunities/)
  assert.doesNotMatch(proposal, /function Closing/)
  assert.doesNotMatch(proposal, /A foundation the firm can keep building from\./)
  assert.doesNotMatch(proposal, /A new chapter, already proven\./)
  assert.match(proposal, /Branding Work/)
  assert.match(proposal, /Website Design/)
  assert.match(proposal, /https:\/\/swim-lang\.github\.io\/blanchet-site\/index\.html/)
  assert.match(proposal, /Password: Dolly/)
  assert.match(proposal, /https:\/\/koplow-defense\.framer\.website\//)
  assert.match(proposal, /https:\/\/sidweberlaw\.com\//)
  assert.match(proposal, /https:\/\/toddburnham\.framer\.website\//)
  assert.match(proposal, /https:\/\/mavenadvocacy\.com\//)
  assert.match(proposal, /https:\/\/lexpolitica\.com\//)
  assert.match(proposal, /https:\/\/burnhamlaw\.com\//)
  assert.match(proposal, /https:\/\/belzerlawfirm\.com\//)
  assert.match(proposal, /https:\/\/pitch\.com\/v\/anchovies-press-zwdsbn/)
  assert.match(proposal, /The Brand Identity/)
  assert.match(proposal, /Best Law Firm Websites 2023/)
  assert.match(proposal, /Best Law Firm Websites 2026/)
  assert.match(proposal, /2025 Award: Good vs\. Great/)
  assert.match(proposal, /Schedule proposal review/)
  assert.match(proposal, /View work/)
  assert.match(proposal, /bg-\[var\(--color-mac\)\]/)
  assert.doesNotMatch(proposal, /Schedule kickoff/)
})
