import { readFileSync } from 'node:fs'
import test from 'node:test'
import assert from 'node:assert/strict'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Soft Hours proposal is registered as Shopify completion scope', () => {
  const app = read('src/App.tsx')
  const manifest = read('src/proposalManifest.json')
  const proposal = read('src/SoftHoursProposal.tsx')
  const contract = read('src/contracts/softHoursContract.ts')

  assert.match(app, /SoftHoursProposal/)
  assert.match(app, /softHoursContract/)
  assert.match(manifest, /Soft Hours/)
  assert.match(manifest, /\/proposal\/soft-hours/)
  assert.match(manifest, /\/proposal\/soft-hours\/contract/)
  assert.match(proposal, /Prepared for Soft Hours/)
  assert.match(proposal, /Shopify Website Completion/)
  assert.match(proposal, /focused sprint to finish the Soft Hours Shopify store/)
  assert.match(proposal, /\$3,000/)
  assert.match(proposal, /Shopify completion sprint/)
  assert.match(proposal, /coded HTML head start/)
  assert.match(proposal, /soft, refined pyjamas brand/)
  assert.match(proposal, /editable Shopify sections/)
  assert.match(proposal, /product uploads, payment and bank setup/)
  assert.match(proposal, /const contractHref = '\/proposal\/soft-hours\/contract'/)
  assert.match(proposal, /Review contract/)
  assert.match(proposal, /Technical intake and build plan/)
  assert.match(proposal, /Client-owned copy placement/)
  assert.match(proposal, /Soft Hours provides final copy/)
  assert.match(proposal, /Mobile QA/)
  assert.match(proposal, /prior mobile direction/)
  assert.match(proposal, /Responsive Shopify review/)
  assert.match(proposal, /Lightweight photography direction/)
  assert.match(proposal, /Priority shot list for homepage, collection, product, fabric, detail, and lifestyle imagery/)
  assert.match(proposal, /Photography production remains client-owned/)
  assert.match(proposal, /launch with confidence/)
  assert.match(proposal, /Previous brand proposal/)
  assert.doesNotMatch(proposal, /Off Menu/)
  assert.doesNotMatch(proposal, /Review proposal/)
  assert.doesNotMatch(proposal, /\$2,850/)
  assert.doesNotMatch(proposal, /\$3,500/)
  assert.doesNotMatch(proposal, /sleepwear/)
  assert.doesNotMatch(proposal, /current Shopify build/)
  assert.doesNotMatch(proposal, /\$7,750/)
  assert.doesNotMatch(proposal, /Meta ad creative kit/)
  assert.doesNotMatch(proposal, /Personal \/ TED site refresh/)
  assert.doesNotMatch(proposal, /Conversion copy support/)
  assert.doesNotMatch(proposal, /Value, benefits, and USP messaging/)
  assert.doesNotMatch(proposal, /conversion-focused copywriting/)
  assert.doesNotMatch(proposal, /campaign pages, photography direction, paid ads/)

  assert.match(contract, /Shopify Website Completion Sprint/)
  assert.match(contract, /fee: '\$3,000'/)
  assert.match(contract, /name: 'Soft Hours'/)
  assert.match(contract, /contactName: 'Marion Voldan'/)
  assert.match(contract, /amount: '\$1,500'/)
  assert.match(contract, /Core page design and development/)
  assert.match(contract, /Editable Shopify sections/)
  assert.match(contract, /Mobile QA, Shopify connection, and launch basics/)
  assert.match(contract, /Lightweight photography direction for launch/)
  assert.match(contract, /Priority shot list for homepage, collection, product, fabric, detail, and lifestyle imagery/)
  assert.match(contract, /Photography production, shooting, editing, and retouching/)
  assert.match(contract, /final payment is not dependent on Soft Hours completing product uploads/)
  assert.match(contract, /Final payment is tied to completion of Anchovies scope/)
  assert.match(contract, /Product uploads/)
  assert.match(contract, /Payment and bank setup/)
  assert.doesNotMatch(contract, /\n    'Photography direction',/)
  assert.doesNotMatch(contract, /Molly Engels/)
})
