import { readFileSync } from 'node:fs'
import test from 'node:test'
import assert from 'node:assert/strict'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Soft Hours proposal is registered as Shopify completion scope', () => {
  const app = read('src/App.tsx')
  const dashboard = read('src/admin/Dashboard.tsx')
  const proposal = read('src/SoftHoursProposal.tsx')

  assert.match(app, /SoftHoursProposal/)
  assert.match(app, /\/proposal\/soft-hours/)
  assert.match(dashboard, /Soft Hours/)
  assert.match(dashboard, /\/proposal\/soft-hours/)
  assert.match(proposal, /Prepared for Soft Hours/)
  assert.match(proposal, /Shopify Website Completion/)
  assert.match(proposal, /focused sprint to finish the Soft Hours Shopify store/)
  assert.match(proposal, /\$3,000/)
  assert.match(proposal, /Shopify completion sprint/)
  assert.match(proposal, /coded HTML head start/)
  assert.match(proposal, /soft, refined pyjamas brand/)
  assert.match(proposal, /editable Shopify sections/)
  assert.match(proposal, /product uploads, payment and bank setup/)
  assert.match(proposal, /mailto:sean@anchovies\.agency\?subject=Accepting%20the%20Soft%20Hours%20Shopify%20Proposal/)
  assert.match(proposal, /Accept proposal/)
  assert.match(proposal, /Technical intake and build plan/)
  assert.match(proposal, /Client-owned copy placement/)
  assert.match(proposal, /Soft Hours provides final copy/)
  assert.match(proposal, /Mobile QA/)
  assert.match(proposal, /prior mobile direction/)
  assert.match(proposal, /Responsive Shopify review/)
  assert.match(proposal, /launch with confidence/)
  assert.match(proposal, /Previous brand proposal/)
  assert.doesNotMatch(proposal, /Off Menu/)
  assert.doesNotMatch(proposal, /Review proposal/)
  assert.doesNotMatch(proposal, /\$2,850/)
  assert.doesNotMatch(proposal, /\$3,500/)
  assert.doesNotMatch(proposal, /sleepwear/)
  assert.doesNotMatch(proposal, /current Shopify build/)
  assert.doesNotMatch(proposal, /\$7,750/)
  assert.doesNotMatch(proposal, /Meta ad creative kit/)
  assert.doesNotMatch(proposal, /Personal \/ TED site refresh/)
  assert.doesNotMatch(proposal, /Conversion copy support/)
  assert.doesNotMatch(proposal, /Value, benefits, and USP messaging/)
  assert.doesNotMatch(proposal, /conversion-focused copywriting/)
})
