import type { ContractData } from './types'

export const cipherContract: ContractData = {
  slug: 'cipher',
  title: 'Brand Identity + Website Engagement',
  preparedDate: 'July 2026',
  agencySignedDate: 'July 2026',
  effectiveDate: '[date both parties sign]',
  projectStart: 'after this Contract is signed and the kickoff invoice is paid',
  timeline: '4 weeks',
  fee: '$15,900',
  client: {
    name: 'Cipher',
    label: 'Client',
    contactName: 'Austin Halvorson and Zach Gregory',
  },
  agency: {
    name: 'Anchovies LLC',
    label: 'Agency',
    address: 'Colorado limited liability company',
  },
  paymentMilestones: [
    {
      amount: '$7,950',
      label: 'Due at project kickoff',
      body: 'This reserves the project window and begins discovery.',
    },
    {
      amount: '$3,975',
      label: 'Due after identity presentation',
      body: 'Due after the primary identity direction has been presented.',
    },
    {
      amount: '$3,975',
      label: 'Due before final handoff',
      body: 'Due before delivery of final files, website transfer, and launch handoff.',
    },
  ],
  revisionRounds: [
    'Discovery and direction: 1 round of refinement on positioning, creative direction, and website goals.',
    'Messaging: 1 round of refinement on core positioning, service language, homepage messaging direction, and key messaging hierarchy.',
    'Visual identity: up to 2 focused refinement rounds after the primary identity direction is presented.',
    'Website design and build: 1 round of refinement on core website design, plus cleanup edits before launch-ready handoff.',
    'Final handoff: 1 round of cleanup edits before final file delivery.',
  ],
  scopePhases: [
    {
      label: 'A',
      title: 'Discovery and direction',
      price: '$2,500',
      timing: 'Week 1',
      includes: [
        'Founder discovery',
        'Business and audience review',
        'Competitive and category review',
        'Positioning opportunities',
        'Brand personality and tone',
        'Website goals',
        'Creative direction moodboards',
      ],
      deliverable:
        'A clear strategic foundation for the Cipher brand, messaging, identity direction, and website goals.',
    },
    {
      label: 'B',
      title: 'Messaging',
      price: 'Included in strategy and messaging',
      timing: 'Week 1 to Week 2',
      includes: [
        'Core positioning',
        'Brand idea',
        'Audience and value proposition',
        'Personality and tone',
        'Short elevator pitch',
        'Homepage messaging direction',
        'Service and capability language',
        'Key messaging hierarchy',
      ],
      deliverable:
        'A focused messaging system that helps Cipher explain a complex offering with clarity, control, and confidence.',
    },
    {
      label: 'C',
      title: 'Visual identity',
      price: '$5,400',
      timing: 'Week 2 to Week 3',
      includes: [
        'Primary logo or wordmark',
        'Secondary logo configuration',
        'Supporting mark or symbol',
        'Typography system',
        'Color system',
        'Graphic and layout language',
        'Digital texture or coded visual language',
        'Social avatar and profile assets',
        'Business card',
        'Pitch deck cover concept',
        'Light brand guidelines',
        'Final identity files',
      ],
      deliverable:
        'A premium, digital-first visual identity system with launch-ready identity files and practical brand guidance.',
    },
    {
      label: 'D',
      title: 'Website design and build',
      price: '$8,000',
      timing: 'Week 3 to Week 4',
      includes: [
        'Website strategy and architecture',
        'Sitemap',
        'Website copywriting',
        'Homepage design',
        'Solutions page design',
        'Outcomes page design',
        'About page design',
        'Contact page design',
        'Responsive desktop and mobile design',
        'Framer development',
        'Contact or inquiry experience',
        'Basic metadata and on-page SEO',
        'Brand implementation',
        'Launch QA',
        'Launch support',
      ],
      deliverable:
        'A focused, responsive five-page Framer website, built to create curiosity, communicate credibility, and support launch.',
    },
  ],
  optionalSupport: [
    'Advanced advertising setup',
    'Media buying support',
    'Analytics dashboards',
    'CRM integrations',
    'Gated content systems',
    'Custom software',
    'Advanced personalization logic',
    'Additional pages or templates',
    'Ongoing brand and website support',
  ],
}
