import type { ContractData } from './types'

export const offMenuContract: ContractData = {
  slug: 'off-menu',
  title: 'Shopify Website, Launch Ads, and Site Refresh',
  preparedDate: 'June 15, 2026',
  agencySignedDate: 'June 15, 2026',
  effectiveDate: '[date both parties sign]',
  projectStart: 'after this Contract is signed and the kickoff invoice is paid',
  timeline: '5 to 6 weeks',
  fee: '$7,750',
  client: {
    name: 'Off Menu',
    label: 'Client',
    contactName: 'Harikrishna Patel',
  },
  agency: {
    name: 'Anchovies LLC',
    label: 'Agency',
    address: 'Colorado limited liability company',
  },
  paymentMilestones: [
    {
      amount: '$4,650',
      label: 'Due at project kickoff',
      body: 'Project starts when the kickoff invoice is paid and Shopify access, product details, and launch references have been shared.',
    },
    {
      amount: '$3,100',
      label: 'Due before final handoff',
      body: 'Due before final handoff, store launch support, ad kit delivery, and personal / TED site refresh handoff.',
    },
  ],
  revisionRounds: [
    'Shopify strategy: 1 round of revisions on the site structure, customer path, app stack, and launch checklist.',
    'Shopify design: 2 rounds of refinement on the core Shopify page designs and mobile direction.',
    'Shopify build: 1 round of implementation fixes before launch.',
    'Website copy: 1 round of refinement on the core page copy, FAQ language, CTA language, and SEO titles/descriptions.',
    'Meta ad creative kit: 1 round of refinement on the selected static ad concepts and message angles.',
    'Personal / TED site refresh: 1 round of visual and copy cleanup before handoff.',
    'Final handoff: 1 round of cleanup edits before final access, assets, and support window delivery.',
  ],
  scopePhases: [
    {
      label: 'A',
      title: 'Shopify strategy, design, and build',
      price: '$5,000',
      timing: 'Week 1 to Week 4',
      includes: [
        'Shopify kickoff',
        'Product and SKU review',
        'Customer path planning',
        'Site architecture',
        'App and integration review',
        'Homepage design',
        'Product page design',
        'Shop / listing page design',
        'About / story page design',
        'FAQ and product education modules',
        'Theme and core page build',
        'Product and collection setup',
        'Navigation and footer setup',
        'Email capture setup',
        'Meta pixel and analytics setup',
        'Foundational SEO setup',
        'Mobile responsive build and launch QA',
      ],
      deliverable:
        'A focused Shopify storefront that explains the product, builds trust, supports mobile shopping, and is ready for launch traffic.',
    },
    {
      label: 'B',
      title: 'Website copy',
      price: 'Included',
      timing: 'Week 2 to Week 4',
      includes: [
        'Homepage copy',
        'Product page copy direction',
        'FAQ copy',
        'About / founder story copy',
        'CTA language',
        'Ad landing page messaging',
        'Microcopy for buttons and forms',
        'SEO titles and descriptions',
      ],
      deliverable:
        'Launch-ready copy for the core Shopify pages, shaped around product understanding, trust, and purchase behavior.',
    },
    {
      label: 'C',
      title: 'Meta ad creative kit',
      price: '$750',
      timing: 'Week 3 to Week 4',
      includes: [
        'Meta ad creative direction',
        '12 static ad concepts',
        '3 message angles',
        'Copy variations',
        'Product-focused ads',
        'Packaging-focused ads',
        'Benefit-led ads',
        'Founder / story-led ads',
        'Launch offer and testing notes',
      ],
      deliverable:
        'A starter batch of static Meta ad creative and message angles for early testing before deeper media spend.',
    },
    {
      label: 'D',
      title: 'Personal / TED site refresh',
      price: '$2,000',
      timing: 'Week 5',
      includes: [
        'Current site review',
        'Visual refresh direction',
        'Homepage / main page redesign',
        'Typography and spacing cleanup',
        'Content hierarchy refinement',
        'Light copy refinement',
        'Speaker / TED section styling',
        'Mobile polish and handoff',
      ],
      deliverable:
        'A lighter, more polished personal / TED site presence that supports the founder story and public credibility around Off Menu.',
    },
    {
      label: 'E',
      title: 'Final QA, launch support, and handoff',
      price: 'Included',
      timing: 'Week 5 to Week 6',
      includes: [
        'Final Shopify QA',
        'Mobile responsive review',
        'Launch support',
        'Ad export handoff',
        'Final refinements',
        'Asset organization',
        'Store access handoff',
        'Post-launch support window',
      ],
      deliverable:
        'A clean launch handoff with the Shopify store, ad kit, refreshed personal site, organized assets, and support window ready to use.',
    },
  ],
  optionalSupport: [
    'Additional ad testing rounds',
    'Video ad concepts',
    'Landing page variants',
    'TikTok Shop creative',
    'Email flows',
    'Product photography direction',
    'Subscription or bundle strategy',
    'A/B testing support',
    'Conversion optimization',
    'Seasonal campaign pages',
    'Investor or retail pitch materials',
    'Ongoing Shopify improvements',
  ],
}
