import type { ContractData } from './types'

export const offMenuContract: ContractData = {
  slug: 'off-menu',
  title: 'Naming and Brand Identity Proposal',
  preparedDate: 'May 2026',
  effectiveDate: '[date both parties sign]',
  projectStart: 'after this Contract is signed and the kickoff invoice is paid',
  timeline: '3 to 4 weeks',
  fee: '$5,850',
  client: {
    name: 'Off Menu',
    label: 'Client',
    contactName: 'Harikrishna Patel',
  },
  agency: {
    name: 'Anchovies LLC',
    label: 'Agency',
    address: 'Colorado limited liability company',
  },
  paymentMilestones: [
    {
      amount: '$3,510',
      label: 'Due at project kickoff',
      body: 'Project starts when the kickoff invoice is paid.',
    },
    {
      amount: '$2,340',
      label: 'Due before final handoff',
      body: 'Before the final asset handoff and starter brand guide delivery.',
    },
  ],
  revisionRounds: [
    'Discovery and creative direction: 1 round of revisions on the creative direction summary and moodboard.',
    'Brand naming: 1 round of refinement on the recommended name direction.',
    'Brand identity system: 2 rounds of refinement after the identity direction is presented.',
    'Packaging direction and mockups: 1 round of refinement on the selected packaging mockup direction.',
    'Social and launch idea: 1 round of refinement on the starter social and launch direction.',
    'Final handoff: 1 round of cleanup edits before final asset delivery.',
  ],
  scopePhases: [
    {
      label: 'A',
      title: 'Discovery and creative direction',
      price: 'Included',
      timing: 'Week 1',
      includes: [
        'Founder and product discovery',
        'Customer and use-case discussion',
        'Category and competitor review',
        'Naming direction discussion',
        'Packaging format discussion',
        'Tone and voice direction',
        'Visual territory exploration',
        'Creative direction moodboard',
      ],
      deliverable:
        'A creative direction summary, moodboard, brand and category observations, and initial direction for naming, identity, and packaging.',
    },
    {
      label: 'B',
      title: 'Brand naming',
      price: '$950',
      timing: 'Week 1 to Week 2',
      includes: [
        'Naming brief',
        'Name territory exploration',
        'Initial name development',
        'One recommended name direction',
        'Domain availability scan',
        'Social handle scan where applicable',
        'Preliminary trademark knockout review',
        'Name rationale',
        'Final name recommendation',
      ],
      deliverable:
        'A focused naming recommendation with rationale, availability notes, and a clear path forward.',
    },
    {
      label: 'C',
      title: 'Brand identity system',
      price: '$4,900',
      timing: 'Week 2 to Week 4',
      includes: [
        'Primary logo',
        'Secondary logo or lockup',
        'Symbol or brand mark if appropriate',
        'Typography system',
        'Color palette',
        'Graphic language or motif',
        'Art direction',
        'Starter tone of voice',
        'Core copy lines',
        'Brand applications',
        'Social/profile asset direction',
        'Foundational brand guide',
      ],
      deliverable:
        'A complete starter identity system that gives Off Menu a clear visual and verbal foundation for packaging, social, digital, and future ecommerce.',
    },
    {
      label: 'D',
      title: 'Packaging direction and mockups',
      price: 'Included',
      timing: 'Week 3 to Week 4',
      includes: [
        'Packaging concept direction',
        'Individual wrap mockup',
        'Outer box, pouch, or carton mockup',
        'Flavor or variant direction if applicable',
        'Material and tactile considerations',
        'Packaging copy direction',
        'Shelf and hand-feel considerations',
        'High-level production notes',
      ],
      deliverable:
        'Packaging mockups and visual recommendations that help guide manufacturer and supplier conversations.',
    },
    {
      label: 'E',
      title: 'Social and launch idea',
      price: 'Included',
      timing: 'Week 3 to Week 4',
      includes: [
        'Launch content themes',
        'TikTok Shop considerations',
        'Social tone direction',
        'Content idea starters',
        'Product education angles',
        'Packaging reveal direction',
        'Starter campaign idea',
      ],
      deliverable:
        'A concise social and launch direction for early content, TikTok Shop, and future social planning.',
    },
    {
      label: 'F',
      title: 'Final handoff',
      price: 'Included',
      timing: 'Week 4',
      includes: [
        'Final logo exports',
        'Color and typography guidance',
        'Starter brand guide',
        'Packaging mockups',
        'Core copy lines',
        'Social and launch direction',
        'Web-ready assets',
        'Organized final files',
      ],
      deliverable:
        'A clean starter brand system that can support manufacturing conversations, packaging development, social planning, and ecommerce.',
    },
  ],
  optionalSupport: [
    'Production packaging design',
    'Shopify website design and development',
    'TikTok Shop launch support',
    'Product page copywriting',
    'Flavor or variant system',
    'Social content templates',
    'Investor or manufacturer pitch materials',
    'Photography art direction',
    'Launch campaign concept',
    'Ongoing brand expansion',
  ],
}
