import type { ContractData } from './types'

export const wildflowerBlancContract: ContractData = {
  slug: 'wildflower-blanc',
  title: 'Brand Identity and Blanc Shopify Website Agreement',
  preparedDate: 'July 3, 2026',
  agencySignedDate: 'July 3, 2026',
  effectiveDate: '[date both parties sign]',
  projectStart: 'after this Contract is signed and the kickoff invoice is paid',
  timeline: '6 to 8 weeks',
  fee: '$16,900',
  client: {
    name: 'Wildflower + Blanc',
    label: 'Client',
    contactName: 'Kelly and Willy',
  },
  agency: {
    name: 'Anchovies LLC',
    label: 'Agency',
    address: 'Colorado limited liability company',
  },
  paymentMilestones: [
    {
      amount: '$8,450',
      label: 'Due at project kickoff',
      body: 'This reserves the project window and begins discovery, brand architecture, and creative direction.',
    },
    {
      amount: '$4,225',
      label: 'Due after identity presentations',
      body: 'Due after the primary identity directions for Wildflower and Blanc have been presented.',
    },
    {
      amount: '$4,225',
      label: 'Due before final handoff',
      body: 'Due before delivery of final identity files, guidelines, and the Blanc website handoff.',
    },
  ],
  revisionRounds: [
    'Discovery and brand architecture: 1 round of revisions on the strategic direction, relationship between brands, and creative direction summary.',
    'Wildflower identity: 2 rounds of refinement after the primary identity direction is presented.',
    'Blanc identity: 2 rounds of refinement after the primary identity direction is presented.',
    'Blanc website strategy and design: 2 rounds of refinement on the core page direction, structure, and visual design.',
    'Blanc website build: 1 round of implementation fixes before launch handoff.',
    'Final handoff: 1 round of cleanup edits before final file delivery and website handoff.',
  ],
  scopePhases: [
    {
      label: 'A',
      title: 'Discovery, brand architecture, and creative direction',
      price: 'Included',
      timing: 'Week 1',
      includes: [
        'Joint founder discovery',
        'Business and audience review',
        'Planner and venue relationship considerations',
        'Competitive and category review',
        'Brand architecture recommendations',
        'Relationship between Wildflower and Blanc',
        'Positioning opportunities for each business',
        'Creative direction moodboards',
        'Photography and visual-content observations',
        'Website and workflow considerations',
      ],
      deliverable:
        'A shared strategic foundation that clarifies what each brand must own and how the two brands should relate.',
    },
    {
      label: 'B',
      title: 'Wildflower brand identity',
      price: '$5,950',
      timing: 'Week 1 to Week 4',
      includes: [
        'Verbal identity',
        'Brand narrative',
        'Primary logo or wordmark',
        'Secondary logo configuration',
        'Supporting mark',
        'Typography system',
        'Color system',
        'Graphic and illustration language',
        'Product naming guidance',
        'Photography and merchandising direction',
        'Business card',
        'Social assets',
        'Crate, vehicle, or delivery application concept',
        'Apparel concept',
        'Canva template system',
        'Mini brand guide',
        'Final identity files',
      ],
      deliverable:
        'A complete Wildflower identity system with visual and verbal tools for planners, customers, deliveries, and marketing.',
    },
    {
      label: 'C',
      title: 'Blanc brand identity',
      price: '$5,950',
      timing: 'Week 1 to Week 4',
      includes: [
        'Verbal identity',
        'Founder and venue narrative',
        'Primary logo or wordmark',
        'Secondary logo configuration',
        'Supporting mark',
        'Typography system',
        'Color system',
        'Graphic language',
        'Venue-specific visual motifs',
        'Photography direction',
        'Business card',
        'Social assets',
        'Signage concept',
        'Inquiry or sales-document concept',
        'Canva template system',
        'Mini brand guide',
        'Final identity files',
      ],
      deliverable:
        'A complete Blanc identity system that positions the venue as a premium, memorable destination with a clear story and visual language.',
    },
    {
      label: 'D',
      title: 'Blanc Shopify website',
      price: '$5,000',
      timing: 'Week 4 to Week 8',
      includes: [
        'Website strategy and architecture',
        'Shopify theme selection or implementation',
        'Custom homepage design',
        'Venue overview',
        'Weddings page',
        'Private and corporate events page',
        'Spaces or property page',
        'Gallery',
        'Founder story',
        'FAQ',
        'Inquiry experience',
        'Mobile and tablet adaptation',
        'Core page copy refinement',
        'Brand implementation',
        'Basic metadata and on-page SEO',
        'Launch QA',
      ],
      deliverable:
        'A premium, inquiry-led Shopify website for Blanc that carries the new venue identity into a practical customer experience.',
    },
    {
      label: 'E',
      title: 'Shared system, final handoff, and launch support',
      price: 'Included',
      timing: 'Week 7 to Week 8',
      includes: [
        'Co-branding hierarchy',
        'Side-by-side logo behavior',
        'Shared versus individual visual elements',
        'Cross-promotion language',
        'Brand-family overview',
        'Final logo exports',
        'Final color and typography guidance',
        'Organized master asset library',
        'Blanc website QA',
        'Shopify handoff notes',
        'Post-handoff support window',
      ],
      deliverable:
        'A clean handoff with both brand systems, shared brand-family guidance, final assets, and the Blanc Shopify website ready for client use.',
    },
  ],
  optionalSupport: [
    'Wildflower Shopify website',
    'Additional Shopify pages or templates',
    'Catalog migration or product entry',
    'Booking or inquiry integrations',
    'Photography art direction',
    'Signage or fabrication coordination',
    'Merchandise and apparel concepts',
    'Seasonal campaign pages',
    'Ongoing brand and website support',
  ],
}
