import type { ContractData } from './types'

export const wildflowerBlancContract: ContractData = {
  slug: 'wildflower-blanc',
  title: 'Dual Brand Identity Engagement',
  preparedDate: 'July 7, 2026',
  agencySignedDate: 'July 7, 2026',
  effectiveDate: '[date both parties sign]',
  projectStart: 'after this Contract is signed and the kickoff invoice is paid',
  timeline: '4 to 5 weeks',
  fee: '$11,900',
  client: {
    name: 'Wildflower + Blanc',
    label: 'Client',
    contactName: 'Kelly and Willy',
  },
  agency: {
    name: 'Anchovies LLC',
    label: 'Agency',
    address: 'Colorado limited liability company',
  },
  paymentMilestones: [
    {
      amount: '$5,950',
      label: 'Due at project kickoff',
      body: 'This reserves the project window and begins discovery, brand architecture, and creative direction.',
    },
    {
      amount: '$2,975',
      label: 'Due after identity presentations',
      body: 'Due after the primary identity directions for Wildflower and Blanc have been presented.',
    },
    {
      amount: '$2,975',
      label: 'Due before final handoff',
      body: 'Due before delivery of final identity files, guidelines, and handoff materials.',
    },
  ],
  revisionRounds: [
    'Discovery and brand architecture: 1 round of revisions on the strategic direction, relationship between brands, and creative direction summary.',
    'Wildflower identity: 2 rounds of refinement after the primary identity direction is presented.',
    'Blanc identity: 2 rounds of refinement after the primary identity direction is presented.',
    'Shared brand system and applications: 1 round of refinement on shared logic, applications, and handoff materials.',
    'Final handoff: 1 round of cleanup edits before final file delivery.',
  ],
  scopePhases: [
    {
      label: 'A',
      title: 'Discovery, brand architecture, and creative direction',
      price: 'Included',
      timing: 'Week 1',
      includes: [
        'Joint founder discovery',
        'Business and audience review',
        'Planner and venue relationship considerations',
        'Competitive and category review',
        'Brand architecture recommendations',
        'Relationship between Wildflower and Blanc',
        'Positioning opportunities for each business',
        'Creative direction moodboards',
        'Photography and visual-content observations',
        'Website and workflow considerations',
      ],
      deliverable:
        'A shared strategic foundation that clarifies what each brand must own and how the two brands should relate.',
    },
    {
      label: 'B',
      title: 'Wildflower brand identity',
      price: '$5,950',
      timing: 'Week 1 to Week 4',
      includes: [
        'Verbal identity',
        'Brand narrative',
        'Primary logo or wordmark',
        'Secondary logo configuration',
        'Supporting mark',
        'Typography system',
        'Color system',
        'Graphic and illustration language',
        'Product naming guidance',
        'Photography and merchandising direction',
        'Business card',
        'Social assets',
        'Crate, vehicle, or delivery application concept',
        'Apparel concept',
        'Canva template system',
        'Mini brand guide',
        'Final identity files',
      ],
      deliverable:
        'A complete Wildflower identity system with visual and verbal tools for planners, customers, deliveries, and marketing.',
    },
    {
      label: 'C',
      title: 'Blanc brand identity',
      price: '$5,950',
      timing: 'Week 1 to Week 4',
      includes: [
        'Verbal identity',
        'Founder and venue narrative',
        'Primary logo or wordmark',
        'Secondary logo configuration',
        'Supporting mark',
        'Typography system',
        'Color system',
        'Graphic language',
        'Venue-specific visual motifs',
        'Photography direction',
        'Business card',
        'Social assets',
        'Signage concept',
        'Inquiry or sales-document concept',
        'Canva template system',
        'Mini brand guide',
        'Final identity files',
      ],
      deliverable:
        'A complete Blanc identity system that positions the venue as a premium, memorable destination with a clear story and visual language.',
    },
    {
      label: 'D',
      title: 'Shared system, final handoff, and launch support',
      price: 'Included',
      timing: 'Week 4 to Week 5',
      includes: [
        'Co-branding hierarchy',
        'Side-by-side logo behavior',
        'Shared versus individual visual elements',
        'Cross-promotion language',
        'Brand-family overview',
        'Final logo exports',
        'Final color and typography guidance',
        'Organized master asset library',
        'Post-handoff support window',
      ],
      deliverable:
        'A clean handoff with both brand systems, shared brand-family guidance, final assets, and practical launch support.',
    },
  ],
  optionalSupport: [
    'Wildflower Shopify website',
    'Blanc Shopify website',
    'Additional Shopify pages or templates',
    'Catalog migration or product entry',
    'Booking or inquiry integrations',
    'Photography art direction',
    'Signage or fabrication coordination',
    'Merchandise and apparel concepts',
    'Seasonal campaign pages',
    'Ongoing brand and website support',
  ],
}
